name: flutterui_modifiers
description: FlutterUI Modifiers is a collection of declarative widget modifiers to make your Flutter code shorter and linear.
version: 0.2.0
author: Lawrence Bensaid <lawrencebensaid@icloud.com>
homepage: https://github.com/lawrencebensaid/flutterui-modifiers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: